# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-04 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Racetrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('track_image', models.ImageField(blank=True, upload_to=b'')),
                ('event_date', models.DateField()),
                ('slug', models.CharField(default='racetrack', max_length=255)),
            ],
            options={
                'ordering': ('event_date',),
            },
        ),
    ]
