# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilotos', '0003_auto_20161111_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piloto',
            options={'ordering': ('numero_dorsal',)},
        ),
    ]
