# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilotos', '0005_piloto_lug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piloto',
            old_name='lug',
            new_name='slug',
        ),
    ]
