# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_remove_equipo_imagen_equipo'),
        ('pilotos', '0006_auto_20161214_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='piloto',
            name='equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipos.Equipo'),
        ),
    ]
