# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pilotos', '0007_piloto_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piloto',
            name='equipo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipos.Equipo'),
        ),
    ]
