# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-02 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotos', '0009_auto_20170331_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='piloto',
            name='fuente',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
