# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-16 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pilotos', '0010_piloto_fuente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piloto',
            name='equipo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipo_del_piloto', to='equipos.Equipo'),
        ),
    ]
