# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pilotos', '0011_auto_20170404_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piloto',
            name='equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipo_del_piloto', to='equipos.Equipo'),
        ),
    ]
