# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-02-10 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotos', '0011_auto_20180416_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='piloto',
            name='estado_competicion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
