# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_remove_equipo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='imagen_equipo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
