# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_equipo_imagen_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='slug',
            field=models.CharField(default=b'equipo', max_length=255),
        ),
    ]
