# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_equipo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='imagen_equipo',
        ),
    ]
