# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotos', '0012_auto_20170404_1410'),
        ('equipos', '0007_equipo_fuente'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='pilotos',
            field=models.ManyToManyField(null=True, related_name='equipos_escuderia', to='pilotos.Piloto'),
        ),
    ]
