# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-16 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotos', '0011_auto_20180416_1131'),
        ('equipos', '0007_equipo_fuente'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='pilotos_del_equipo',
            field=models.ManyToManyField(blank=True, related_name='pilotos_del_equipo', to='pilotos.Piloto'),
        ),
    ]
