# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-22 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0008_equipo_pilotos_del_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='estado',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
