# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0008_equipo_pilotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='pilotos',
        ),
    ]
