# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-04 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('team_image', models.ImageField(blank=True, upload_to=b'')),
                ('source', models.CharField(blank=True, max_length=255)),
                ('history', models.TextField()),
                ('slug', models.CharField(default='team', max_length=255)),
                ('team_riders', models.ManyToManyField(blank=True, related_name='team_riders', to='riders.Rider')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
