# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circuito',
            options={'ordering': ('nombre',)},
        ),
        migrations.RemoveField(
            model_name='circuito',
            name='fecha',
        ),
    ]
