# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0002_auto_20161031_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuito',
            name='imagen_trazado',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
