# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0006_auto_20161111_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuito',
            name='fecha_evento',
            field=models.DateField(),
        ),
    ]
