# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0007_auto_20161111_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circuito',
            options={'ordering': ('fecha_evento',)},
        ),
    ]
