# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0012_remove_circuito_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuito',
            name='slug',
            field=models.CharField(default=b'circuito', max_length=255),
        ),
    ]
