# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 08:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0013_circuito_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuito',
            name='fecha_hoy',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
