# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0014_circuito_fecha_hoy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuito',
            name='fecha_hoy',
        ),
    ]
