# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='fecha_noticia',
            field=models.TimeField(auto_now=True),
        ),
    ]
