# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-06 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_fecha_noticia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-fecha_noticia']},
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha_noticia',
            field=models.DateField(auto_now=True),
        ),
    ]
