# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-14 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20170406_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='fecha_noticia',
        ),
        migrations.AddField(
            model_name='noticia',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
