# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-16 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_auto_20171116_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
