# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-03 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_auto_20171116_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='idioma',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
