# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-03 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0007_noticia_idioma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='idioma',
        ),
    ]
