# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-03 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0008_remove_noticia_idioma'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='idioma',
            field=models.CharField(default='NO_LANG', max_length=10),
            preserve_default=False,
        ),
    ]
