# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-04 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('biography', models.TextField()),
                ('rider_profile', models.ImageField(blank=True, upload_to=b'')),
                ('source', models.CharField(blank=True, max_length=255)),
                ('rider_number', models.IntegerField(default=0)),
                ('slug', models.CharField(default='piloto', max_length=255)),
            ],
            options={
                'ordering': ('rider_number',),
            },
        ),
    ]
