# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-04 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_rider_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='slug',
            field=models.CharField(default='rider', max_length=255),
        ),
    ]
