# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-02-10 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0003_auto_20180504_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='competition_status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
